
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores.compiladores;

/** CUP generated interface containing symbol constants. */
public interface Simbolos {
  /* terminals */
  public static final int COMMA = 4;
  public static final int NUM = 3;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int UNKNOWN_TOKEN = 6;
  public static final int OP_ASSIGN = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "NUM",
  "COMMA",
  "OP_ASSIGN",
  "UNKNOWN_TOKEN"
  };
}

